### ISSUE TITLE
Any idea why OpenWRT gives me this error trying to use pytap2 ? OSError: [Errno 81] File descriptor in bad state

### ISSUE THREAD

**Issue by markbirss** [johnthagen/pytap2#9]
Hi

Anyone can help understanding why using pytap2 on OpenWRT would gives this error ?

```
from pytap2 import TapDevice

with TapDevice() as device:
    device.ifconfig(mtu=1300)
    device.write(b'0000')

```

```
(tmp) root@OpenWrt:/tmp/tmp# python3 do.py
Traceback (most recent call last):
  File "/tmp/tmp/do.py", line 3, in <module>
    with TapDevice() as device:
  File "/tmp/tmp/lib/python3.9/site-packages/pytap2/__init__.py", line 75, in __init__
    ifs = fcntl.ioctl(
OSError: [Errno 81] File descriptor in bad state
```

**Comment by johnthagen** [comment]
I have only tried `pytap2` on Ubuntu/CentOS variants before, so I'm not sure if OpenWRT has differences or not.

You can also try [`python-pytun`](https://pypi.org/project/python-pytun/) which is very similar to `pytap(2)`

**Comment by markbirss** [comment]
@johnthagen thank you for your feedback
